spring:
  application:
    name: gateway-zuul
server:
  port: 8040
  
eureka:
  client:
    service-url:
      defaultZone: http://user:admin123@localhost:8761/eureka
  instance:
    ip-address: true
    
zuul:
  routes:
    users: 
      path: /user-url/**
      service-id: provider-user

ribbon:
  eureka:
    enabled: false

provider-user:
  ribbon:
    listOfServers: http://localhost:7900,http://localhost:7901