server:
  port: 8010
spring:
  application:
    name: consumer-movie-ribbon

  
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:admin123@localhost:8761/eureka
      
provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule