server:
  port: 7901
spring:
  application:
    name: consumer-movie
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:admin123@localhost:8761/eureka
  instance:
    prefer-ip-address: true

    