server:
  port: 7901
spring:
  application:
    name: consumer-movie
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:admin123@localhost:8761/eureka
      
logging:
  level:
    com.springcloud.UserFeignClient: debug

    